version: '3'

services:
  vault:
    image: hashicorp/vault:1.19
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
      VAULT_DEV_ROOT_TOKEN_ID: 'myroot'
    healthcheck:
      test: |
        vault status -address=http://localhost:8200
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 1s
    cap_add:
      - IPC_LOCK
    networks:
      - intranet

  setup:
    image: hashicorp/vault:1.19
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "myroot"
    depends_on:
      vault:
        condition: service_healthy
    networks:
      - intranet
    command:
      - "/bin/sh"
      - "-c"
      - "vault secrets enable transit; vault write -f transit/keys/testkey"

networks:
  intranet:
