name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build (No CGO)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [stable, oldstable]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Setup
      if: runner.os == 'Linux'
      run: make setup

    - name: Check
      run: make check
      env:
        CGO_ENABLED: "0"

    - name: Upload Code Coverage
      if: runner.os == 'Linux'
      run: bash <(curl -s https://codecov.io/bash)
